# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   +-------------------------------------------------------------------------------+ #
#    _____ _____ ____  _____ _____ __ __ _____ __    _____ _____ _____ _____ _____ _  #
#    |  |  |     |    \|   __|     |  |  |  _  |  |  |  |  |   __|     |   | |   __|  #
#    |     |-   -|  |  |   __| | | |_   _|   __|  |__|  |  |  |  |-   -| | | |__   |  #
#    |__|__|_____|____/|_____|_|_|_| |_| |__|  |_____|_____|_____|_____|_|___|_____|  #
#   +-------------------------------------------------------------------------------+ #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# # # # # # # # # # #
#  +--------------+ #
#      Database     #
#  +--------------+ #
# # # # # # # # # # #

# SQLite (This option only works for Spigot. You will need to use MySQL if you use BungeeCord.)
use-sqlite: true
SQLite:
  filename: "database"
  table_name: "hmp"

# MySQL
use-mysql: false
MySQL:
  host: "localhost"
  port: 3306
  database: "hidemyplugins"
  user: "user"
  password: "123"
  table_name: "hmp"

# Don't touch anything of these unless you have knowlege.
# Touching this configuration without knowing what this does
# can result in the MySQL Connection to not start.
#
# This is an advanced option, if you know what are you doing this
# option allows you to change the SQL protocol.
database-driver: "jdbc:mysql://"
database-class: "com.mysql.jdbc.Driver"

# # # # # # # # # # #
#  +--------------+ #
#   Tab Completion  #
#  +--------------+ #
# # # # # # # # # # #

# This option will enable/disable loggin from players who use
# the TAB COMPLETION method to look up into plugins.
# It is recomended that you turn this off if you use MC 1.14 or
# newer since this can annoy users...
tabCompletionLoggin: true

# This option will enable/disable title alerts to players who use
# the TAB COMPLETION method. It is recomended that you turn this off
# if you use MC 1.14 or newer, since this can annoy users...
tabCompletionAlert: false

# # # # # # # # # # #
#  +--------------+ #
#      Commands     #
#  +--------------+ #
# # # # # # # # # # #

# This will notify everyone with the notify permission if a player
# uses a blocked command.
adminNotify: true

# This option will enable/disable title alerts to players who use
# blocked commands.
blockedCommandAlert: true

# Here are some commands that are blocked to regular users.
# You can add more commands to block if you like.
blockedCommands:
  - 'help'
  - 'plugins'
  - 'about'
  - 'icanhasbukkit'
  - 'bukkit'
  - 'minecraft'
  - '?'
  - 'pl'
  - 'ver'
  - 'version'
  - 'info'
  - 'calc'
  - 'eval'
  - '/calc'
  - '/eval'
  - 'plugman'

# Here you can whitelist commands that got blocked.
# If a command is blocked like minecraft:tell you can unblock it here.
whitelistedCommands:
  - 'minecraft:tell'

# # # # # # # # # # #
#  +--------------+ #
#       Sounds      #
#  +--------------+ #
# # # # # # # # # # #

sounds:
  # Enable or disable sounds.
  enable-sounds: false

  # Set the type of sound here, you can find a list of
  # sounds here.
  #
  # If you use minecraft 1.9x - 1.15.2 or newer use this sound list.
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  #
  # If you use minecraft 1.8x use this sound list.
  # https://pastebin.com/ykhFMPuy
  blocked-command-sound:
    - 'ENTITY_ENDERMAN_SCREAM'
    - 'ENTITY_ENDERMAN_DEATH'

# # # # # # # # # # #
#  +--------------+ #
#    Stealth Mode   #
#  +--------------+ #
# # # # # # # # # # #

# Stealth Mode allows you to hide all HideMyPlugins commands to normal users.
stealth-mode:
  enabled: false
  command-not-found: Unknown command. Type "/help" for help.

# # # # # # # # # # #
#  +--------------+ #
#   Web Interface   #
#  +--------------+ #
# # # # # # # # # # #
# https://github.com/Gamerexde/hidemyplugins-web-interface/

# Allow this option if you're currently using HideMyPlugins Web Interface.
UsingWebInterface: false

# Here you will put the domain where HideMyPlugins Web is currently at.
WebInterface: "https://gamerexde.com/hidemyplugins"