# _   _ _     _     ___  ___     ______ _             _
#| | | (_)   | |    |  \/  |     | ___ \ |           (_)
#| |_| |_  __| | ___| .  . |_   _| |_/ / |_   _  __ _ _ _ __  ___
#|  _  | |/ _` |/ _ \ |\/| | | | |  __/| | | | |/ _` | | '_ \/ __|
#| | | | | (_| |  __/ |  | | |_| | |   | | |_| | (_| | | | | \__ \
#\_| |_/_|\__,_|\___\_|  |_/\__, \_|   |_|\__,_|\__, |_|_| |_|___/
#                            __/ |               __/ |           2.1.2
#                           |___/               |___/
#                           By Gamerexde
#
#

# Here are some commands that are blocked to regular users.
# You can add more commands to block if you like.
blockedCommands:
  - 'help'
  - 'plugins'
  - 'about'
  - 'icanhasbukkit'
  - 'bukkit'
  - 'minecraft'
  - '?'
  - 'help'
  - 'pl'
  - 'ver'
  - 'version'

# Message that players recive when they don't have permission to access blocked commands.
