name: HideMyPlugins
version: ${project.version}
main: com.gamerexde.HideMyPlugins.Main
depend: [ProtocolLib]
authors: [Gamerexde]
description: The best way to protect your plugins.
website: https://gamerexde.pro/
commands:
  hidemyplugins: