name: HideMyPlugins
version: ${project.version}
main: com.gamerexde.hidemyplugins.hidemyplugins.HideMyPlugins
depend: [ProtocolLib]
authors: [Gamerexde]
description: The best way to protect your plugins.
website: https://gamerexde.pro/
