name: HideMyPlugins
version: ${project.version}
main: pro.gamerexde.hidemyplugins.HideMyPlugins
depend: [ProtocolLib]
authors: [Gamerexde]
description: The best way to protect your plugins.
website: https://gamerexde.pro/
commands:
  hidemyplugins: