name: HideMyPlugins
version: 2.1-BETA
main: com.gamerexde.hidemyplugins.hidemyplugins.HideMyPlugins
depend: [ProtocolLib]
authors: [Gamerexde]
description: The best way to protect your plugins.
website: https://gamerexde.pro/
