name: HideMyPlugins
version: 2.2.0-SNAPSHOT
main: pro.gamerexde.hidemyplugins.HideMyPlugins
depend: [ProtocolLib]
authors: [Gamerexde]
description: The best way to protect your plugins.
website: https://gamerexde.pro/
commands:
  hidemyplugins: